const userAuth = async(req,res)=>{
    try{
        
    }catch(err){
        console.log(err);
    }
}